import { Schedule, User } from '../types';

export const exportToPDF = (schedule: Schedule, user: User) => {
  // Create a simple HTML structure for PDF generation
  const content = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Daily Schedule - ${user.firstName} ${user.surname}</title>
      <style>
        body {
          font-family: 'Inter', Arial, sans-serif;
          margin: 20px;
          background: white;
          color: #333;
        }
        .header {
          text-align: center;
          margin-bottom: 30px;
          padding-bottom: 20px;
          border-bottom: 2px solid #00e0ff;
        }
        .user-info {
          font-size: 14px;
          color: #666;
          margin-bottom: 10px;
        }
        .task {
          margin: 15px 0;
          padding: 10px;
          border-left: 4px solid #00e0ff;
          background: #f8f9fa;
        }
        .task-time {
          font-weight: bold;
          color: #00e0ff;
        }
        .task-title {
          margin: 5px 0;
          font-size: 16px;
        }
        .priority {
          display: inline-block;
          padding: 2px 8px;
          border-radius: 12px;
          font-size: 12px;
          font-weight: bold;
        }
        .priority-high { background: #ff6b6b; color: white; }
        .priority-medium { background: #ffd93d; color: #333; }
        .priority-low { background: #6bcf7f; color: white; }
        .quote {
          margin-top: 30px;
          padding: 20px;
          background: #f0f8ff;
          border-left: 4px solid #ff6bff;
          font-style: italic;
          text-align: center;
          font-size: 18px;
        }
        .footer {
          margin-top: 30px;
          text-align: center;
          font-size: 12px;
          color: #666;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Daily Task Schedule</h1>
        <div class="user-info">${user.firstName} ${user.surname} • ${user.email}</div>
        <div class="user-info">${new Date(schedule.date).toLocaleDateString('en-US', { 
          weekday: 'long', 
          year: 'numeric', 
          month: 'long', 
          day: 'numeric' 
        })}</div>
      </div>
      
      ${schedule.tasks.map(task => `
        <div class="task">
          <div class="task-time">${task.timeStart} - ${task.timeEnd}</div>
          <div class="task-title">${task.title}</div>
          <span class="priority priority-${task.priority}">${task.priority.toUpperCase()}</span>
        </div>
      `).join('')}
      
      <div class="quote">
        "${schedule.quote}"
      </div>
      
      <div class="footer">
        Generated by Daily Task Scheduler • Dark-Neon Edition
      </div>
    </body>
    </html>
  `;

  // Create a blob and download
  const blob = new Blob([content], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `Schedule-${new Date().toISOString().split('T')[0]}-${user.firstName}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};